### PR TITLE
#38, empty contact code field fix, more style fixes, cleanup

### LINKED ISSUE #38: Fix registration button styling, add contact code CTA
Contact code box for new registration should contain CTA reading `Grant access`:
image

Button styling during registration should be a right-aligned link with arrow: 
image

Link on first screen should read `Register`

Link on T&Cs screen should read `Send SNT`

### PR DESCRIPTION
**Pull request by alwx**
Fixes #38
Also fixes empty contact code field error and adds better error handling (now you can at least see what's up and what is the error)

### CODE REVIEW

**Comment by jeluard** [comment]
@alwx Please resolve conflicts :)

File: app/actions/accounts.js [hunk 1]
```diff
@@ -23,15 +23,16 @@ export const fetchAndDispatchAccountsWithBalances = (web3, dispatch) => {
     }
   })
 }
-export const checkAndDispatchStatusContactCode = dispatch => {
+export const checkAndDispatchStatusContactCode = (dispatch, callback) => {
```
Comment (bgits) [inline app/actions/accounts.js]: You should not need a callback for dispatching an action, you should instead subscribe the component to the slice of the state it updates. Doing this seems error prone.

File: app/components/ens/registerSubDomain.js [hunk 2]
```diff
@@ -18,136 +17,162 @@ import {generateXY} from '../../utils/ecdsa';
...
-          <Terms open={displayTerms(status)} onSubmit={() => { setStatus(null); formRef.current.dispatchEvent(new Event('submit')) }} form={formRef} />
-        </div>
-      </Hidden>
-    </div>
-  </form>
-);
+class InnerForm extends React.Component {
+  requestStatusContactCode = ({getStatusContactCode, setValues, values}) => {
+    getStatusContactCode((result) => {
+      setValues({...values, statusAddress: result});
```
Comment (bgits) [inline app/components/ens/registerSubDomain.js]: Why is `statusAddress` needed? can't `statusContactCode` from the `mapPropsToState` be used?
